import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { HeaderComponent } from "@/components/Header/header";
import { FooterComponent } from "@/components/footer";
import { Providers } from "@/contexts/Theme/provider-theme";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} dark:bg-red`} suppressHydrationWarning>
      <body>
        <Providers>
          <HeaderComponent />
          <main className="flex flex-col">
            {children}
          </main>
          <FooterComponent />
        </Providers>
      </body>
    </html>
  );
}
