import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import {ThemeProvider} from "@/contexts/Theme/theme-provider";
import {HeaderComponent} from "@/components/Header/header";
import {FooterComponent} from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <ThemeProvider>
        <HeaderComponent/>
        <main className="flex flex-col bg-white dark:bg-black">
          {children}
        </main>
        <FooterComponent/>
      </ThemeProvider>
    </html>
  );
}
